# name: Automatically publish tagged builds
# on:
#   push:
#     tags:
#       - v*

# jobs:
#   create-release:
#     name: Create release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Get latest release
#         id: last_release
#         uses: InsonusK/get-latest-release@v1.0.1
#         with:
#           myToken: ${{ secrets.GITHUB_TOKEN }}
#           exclude_types: "draft"
#           view_top: 1
#       - name: Create release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}